### ISSUE TITLE
Massive Lag spikes caused by experience adjudication task

### ISSUE THREAD

**Issue by MithrandirCraft** [dmulloy2/SwornRPG#30]
Aparently, when someone kills a mob, and gets experience for it, the whole server lags because of a very specific experience task:

http://i.imgur.com/gNgjdKH.png

I just thought I would mention it, allthough I wont be using this plugin any more at the moment.

It's been fun having this plugin on my server, so I would like to thank you for making it :)

I will be relying on other plugins for sitting and marrying xD

**Comment by dmulloy2** [comment]
Just set ````levelingMethods.mobKills.enabled```` to false if it's an issue.

**Comment by dmulloy2** [comment]
As it turns out, having a high camping radius (like the default value, unfortunately) causes a bulk of the lag in the timings.  Setting it to a lower value (or just -1 to disable) fixes the problem.
