### ISSUE TITLE
BUG - To many given upon level up?

### ISSUE THREAD

**Issue by Inysal** [dmulloy2/SwornRPG#33]
So the possible issue I have encountered is during  Player Level Up, (default) Level one, they get 
1 Diamond

Then Level up, Level 2, they get
2 Diamond

This goes on, and on, so by level 10, they will have Total of 55 Diamonds from
level 1 to level 10.  It would be great if you could only get one diamond per level.

Spigot 1.10.2
SwornRPG v3.3

How to resolve this so everyone is happy, if this isn't a bug:

Add additional config line, for example.

levelingRewards:
  enabled: true
  *increase money per level: true / false
 * increase item per level: true / false
  money: 250
  items:
    - "diamond, 1"

Please and thank you for your support!

**Comment by dmulloy2** [comment]
This is the intended behavior. I can look into adding a toggle though.

**Comment by Inysal** [comment]
That would be great thank you! I guess from my other reports, the intended behavior does not work for my server. I am thankful this works without really any issues on 1.10.2. There are alot of Plugins that aren't being updated anymore.
