### ISSUE TITLE
Bug - Placing Blocks - get same block back chance broken.

### ISSUE THREAD

**Issue by Inysal** [dmulloy2/SwornRPG#35]
Spigot 1.10.2
SwornRPG v3.3

The issue I am having, which I don't see a config, in the config file for this is, when players place down blocks, they are getting blocks back at a random value, however, I am alright with this, but according to my staff. Coal blocks and Quarts so far, are giving a large amount back. Reviewing the site and config file a fews times. I don't see anything about blocks being placed, and the chance of getting one back. All I know of is breaking them.

If this is a bug, a simple fix would be to have settings in the config file 

1 universal setting, 1 out of chance

block_place_return: true / false
block_place_return: (chance range)

Thanks for your help.

**Comment by dmulloy2** [comment]
By the current design, the chance is calculated based on the player's level, not the type of the block.

**Comment by Inysal** [comment]
Okay I see. I understand that, though is there anyway you could add this in the configuration file maybe as a universal chance, as well a enable / disable. That would be great. ^^
