### ISSUE TITLE
BUG - Standup Command - Invalid Packet Kick

### ISSUE THREAD

**Issue by Inysal** [dmulloy2/SwornRPG#37]
Spigot 1.10.2
SwornRPG 3.3

in game: /sit
In game: /standup
Log: Inysal lost connection: Invalid move player packet received
Then you get kicked from the Server.

**Comment by dmulloy2** [comment]
Yeah I tried a bunch of things to get it to work properly but it seems to be an issue with how Craftbukkit handles sitting. If someone has a solution, that'd be great, but for now there's nothing I can think of.

**Comment by Inysal** [comment]
Hey D. Mulloy,

I just wanted to let you know if anyone complains about this same bug, or if you want to look at your code. Instead of using /standup, if you use /stand you don't get the same issue where you get kicked.

**Comment by dmulloy2** [comment]
That's odd. They should be the same command.
